INSERT INTO quizzes (id, title, quiz_type, created_by_id, is_active) VALUES ('544dc945-1109-45b8-a295-2a23cb4579ed', '03_Vorsorgeuntersuchungen - LOW', 'LESSON', 'eaa07e4f-6a76-4781-93e0-49dbfc7edb43', true) ON CONFLICT (id) DO NOTHING;
WITH inserted_question_0 AS (INSERT INTO questions (quiz_id, question_text, question_type, expected_answer, order_index) VALUES ('544dc945-1109-45b8-a295-2a23cb4579ed', '**Szenario-Analyse / Gesundheitliche Folgen**

Ein Mitarbeiter klagt nach der Einführung neuer Bildschirme über Nackenschmerzen und schnelle Ermüdung. Bei einer Begehung stellen Sie fest: Der Monitor steht auf einem PC-Gehäuse auf dem Tisch, die oberste Zeile befindet sich deutlich über Augenhöhe. Der Mitarbeiter trägt eine Gleitsichtbrille. Was ist die wahrscheinliche physiologische Ursache für die Beschwerden basierend auf den Dokumentinhalten?', 'MCQ', NULL, 1) ON CONFLICT DO NOTHING RETURNING id) INSERT INTO options (question_id, option_text, is_correct, explanation) SELECT (SELECT id FROM inserted_question_0), 'Die Bildwiederholfrequenz ist zu niedrig eingestellt.', false, NULL UNION ALL SELECT (SELECT id FROM inserted_question_0), 'Der Mitarbeiter legt den Kopf in den Nacken, um durch den unteren Teil der Brille scharf zu sehen, da der Monitor zu hoch steht.', true, 'Das Dokument fordert, dass die oberste Zeile unter Augenhöhe ist und unnatürliche Kopfhaltungen vermieden werden. Steht der Monitor zu hoch, muss der Mitarbeiter den Kopf nach hinten neigen ("Geierhals"), was zu den beschriebenen Nackenschmerzen führt.

**Warum andere falsch:** A, C und D könnten Probleme verursachen, erklären aber nicht spezifisch die Kombination aus Nackenschmerzen und der beobachteten viel zu hohen Monitorposition.

**💡 Wichtige Erkenntnis:** Die Monitorhöhe hat direkten Einfluss auf die Halswirbelsäule. "Runter mit dem Monitor" ist oft die erste Hilfe bei Nackenproblemen.' UNION ALL SELECT (SELECT id FROM inserted_question_0), 'Der Monitor ist zu klein für die Arbeitsaufgabe.', false, NULL UNION ALL SELECT (SELECT id FROM inserted_question_0), 'Die Tastatur hat keine Handballenauflage.', false, NULL;
WITH inserted_question_1 AS (INSERT INTO questions (quiz_id, question_text, question_type, expected_answer, order_index) VALUES ('544dc945-1109-45b8-a295-2a23cb4579ed', '**Rechtliche Rahmenbedingungen / Synthese Sie**

sollen für ein deutsches Unternehmen ein Konzept für Bildschirmarbeitsplätze erstellen. Welche rechtliche Hierarchie und Zusammensetzung von Vorschriften müssen Sie laut Dokument beachten?', 'MCQ', NULL, 2) ON CONFLICT DO NOTHING RETURNING id) INSERT INTO options (question_id, option_text, is_correct, explanation) SELECT (SELECT id FROM inserted_question_1), 'EU-Richtlinien stehen über allem, deutsche Gesetze wie die BildscharbV sind nicht mehr gültig.', false, NULL UNION ALL SELECT (SELECT id FROM inserted_question_1), 'Nur das Arbeitsschutzgesetz (ArbSchG), da es alle anderen Regeln ersetzt.', false, NULL UNION ALL SELECT (SELECT id FROM inserted_question_1), 'Eine Kombination aus EU-Richtlinien, nationalen Gesetzen (ArbSchG), Verordnungen (ArbStättV, BildscharbV) und Berufsgenossenschaftlichen Vorschriften.', true, 'Das Dokument zeigt eine geschichtete Struktur: EU-Rahmenrichtlinien geben den Rahmen vor, in Deutschland umgesetzt durch ArbSchG, konkretisiert durch Verordnungen (ArbStättV, BildscharbV) und Unfallverhütungsvorschriften der Berufsgenossenschaften.

**Warum andere falsch:** A ist zu allgemein (ArbSchG ist ein Rahmengesetz). B ist falsch, nationale Gesetze setzen EU-Recht um. D ist falsch, Normen (DIN) werden genannt, sind aber nicht die einzige Quelle; Gesetze sind vorrangig.

**💡 Wichtige Erkenntnis:** Compliance im Arbeitsschutz erfordert die Beachtung eines ganzen Bündels an Vorschriften, von der EU-Ebene bis zur Unfallverhütungsvorschrift.' UNION ALL SELECT (SELECT id FROM inserted_question_1), 'Die DIN-Normen sind die einzigen rechtlich bindenden Vorschriften.', false, NULL;
WITH inserted_question_2 AS (INSERT INTO questions (quiz_id, question_text, question_type, expected_answer, order_index) VALUES ('544dc945-1109-45b8-a295-2a23cb4579ed', '**Software-Ergonomie / Usability Bewertung**

Ein Unternehmen führt eine neue Software ein. Die Software ist zwar fehlerfrei, aber die Mitarbeiter beschweren sich, dass die Menüführung unlogisch ist, bekannte Symbole (wie das Diskettensymbol zum Speichern) durch abstrakte neue Icons ersetzt wurden und sie viel länger für Standardaufgaben brauchen. Welches Kernprinzip der Software-Ergonomie (gemäß ISO 9241 / Mindmap) wird hier primär verletzt und welche Usability-Komponente leidet darunter?', 'MCQ', NULL, 3) ON CONFLICT DO NOTHING RETURNING id) INSERT INTO options (question_id, option_text, is_correct, explanation) SELECT (SELECT id FROM inserted_question_2), 'Verletzung der "Lernförderlichkeit" (Erwartungskonformität); negative Auswirkung auf die Effizienz.', true, 'Die Mindmap nennt unter Lernförderlichkeit die "Verwendung einheitlicher und bekannter Begriffe, Zeichen und Symbole". Werden diese missachtet, ist die Software nicht intuitiv. Dies führt dazu, dass Mitarbeiter länger brauchen, was die Effizienz (Nutzbarkeit) senkt.

**Warum andere falsch:** Fehlertoleranz (B) betrifft Fehleingaben. Anpassbarkeit (C) betrifft Konfigurationen. Aufgabenangemessenheit (D) ist relevant, aber das spezifische Problem der unverständlichen Icons gehört zur Lernförderlichkeit.

**💡 Wichtige Erkenntnis:** Ergonomie heißt auch kognitive Entlastung. Software muss sich so verhalten, wie der Nutzer es aufgrund seiner Erfahrung erwartet.' UNION ALL SELECT (SELECT id FROM inserted_question_2), 'Verletzung der "Fehlertoleranz"; negative Auswirkung auf die Individualisierbarkeit.', false, NULL UNION ALL SELECT (SELECT id FROM inserted_question_2), 'Verletzung der "Anpassbarkeit"; negative Auswirkung auf die Systemrückmeldung.', false, NULL UNION ALL SELECT (SELECT id FROM inserted_question_2), 'Verletzung der "Aufgabenangemessenheit"; negative Auswirkung auf die Fehlermeldung.', false, NULL;
INSERT INTO enabler_quiz_links (enabler_id, quiz_id, difficulty) VALUES ('f5bdaf4c-ee94-48be-b1bd-e66390d0a262', '544dc945-1109-45b8-a295-2a23cb4579ed', 'LOW') ON CONFLICT DO NOTHING;
INSERT INTO quizzes (id, title, quiz_type, created_by_id, is_active) VALUES ('37d31e3a-0528-4801-b946-cb76d8c80a9b', '07_Verhaltensweisen im Brandfall sowie vorbeugender Brandschutz - LOW', 'LESSON', 'eaa07e4f-6a76-4781-93e0-49dbfc7edb43', true) ON CONFLICT (id) DO NOTHING;
WITH inserted_question_0 AS (INSERT INTO questions (quiz_id, question_text, question_type, expected_answer, order_index) VALUES ('37d31e3a-0528-4801-b946-cb76d8c80a9b', '**Arbeitsschutzgesetz (ArbSchG)**

Was ist das Hauptziel des Arbeitsschutzgesetzes (ArbSchG)?', 'MCQ', NULL, 1) ON CONFLICT DO NOTHING RETURNING id) INSERT INTO options (question_id, option_text, is_correct, explanation) SELECT (SELECT id FROM inserted_question_0), 'Die Erhöhung der wöchentlichen Arbeitszeit zur Steigerung der Produktivität.', false, NULL UNION ALL SELECT (SELECT id FROM inserted_question_0), 'Die Regelung der Vergütung von Überstunden und Nachtarbeit.', false, NULL UNION ALL SELECT (SELECT id FROM inserted_question_0), 'Die Verbesserung der Sicherheit und des Gesundheitsschutzes der Beschäftigten bei der Arbeit .', true, 'Das Dokument definiert das ArbSchG als "Gesetz über die Durchführung von Maßnahmen des Arbeitsschutzes zur Verbesserung der Sicherheit und des Gesundheitsschutzes der Beschäftigten bei der Arbeit" .

**Warum andere falsch:** A, B und D betreffen andere Bereiche des Arbeitsrechts (Arbeitszeitgesetz, Bundesurlaubsgesetz etc.), sind aber nicht das primäre Ziel des Arbeitsschutzgesetzes.

**💡 Wichtige Erkenntnis:** Das ArbSchG ist die zentrale rechtliche Grundlage in Deutschland, die Arbeitgeber zur Gewährleistung von Sicherheit und Gesundheitsschutz verpflichtet.' UNION ALL SELECT (SELECT id FROM inserted_question_0), 'Die Festlegung der Mindestanzahl an Urlaubstagen für Arbeitnehmer.', false, NULL;
WITH inserted_question_1 AS (INSERT INTO questions (quiz_id, question_text, question_type, expected_answer, order_index) VALUES ('37d31e3a-0528-4801-b946-cb76d8c80a9b', '**DGUV**

Wofür steht die Abkürzung DGUV im Kontext der Unfallverhütung?', 'MCQ', NULL, 2) ON CONFLICT DO NOTHING RETURNING id) INSERT INTO options (question_id, option_text, is_correct, explanation) SELECT (SELECT id FROM inserted_question_1), 'Deutscher Gewerkschafts- und Unfall-Verbund', false, NULL UNION ALL SELECT (SELECT id FROM inserted_question_1), 'Dienstleistungs-Gewerkschaft für Unternehmer-Verantwortung', false, NULL UNION ALL SELECT (SELECT id FROM inserted_question_1), 'Deutsche Gesetzliche Unfallversicherung', true, 'Das Dokument verwendet die Abkürzung DGUV und der ausgeschriebene Name "Deutsche Gesetzliche Unfallversicherung" wird im Kontext der Unfallverhütungsvorschriften genannt (obwohl nicht explizit ausgeschrieben, ist dies der Standardbegriff für die Träger der gesetzlichen Unfallversicherung in Deutschland).

**Warum andere falsch:** A, B und D sind falsche Bezeichnungen.

**💡 Wichtige Erkenntnis:** Die DGUV ist der Spitzenverband der gewerblichen Berufsgenossenschaften und der Unfallkassen, die für die Prävention und Absicherung von Arbeitsunfällen zuständig sind.' UNION ALL SELECT (SELECT id FROM inserted_question_1), 'Deutsches Gremium für Unternehmens-Vorschriften', false, NULL;
WITH inserted_question_2 AS (INSERT INTO questions (quiz_id, question_text, question_type, expected_answer, order_index) VALUES ('37d31e3a-0528-4801-b946-cb76d8c80a9b', '**Arbeit 4.0**

Wodurch ist der Begriff "Arbeit 4.0" laut Dokument primär gekennzeichnet?', 'MCQ', NULL, 3) ON CONFLICT DO NOTHING RETURNING id) INSERT INTO options (question_id, option_text, is_correct, explanation) SELECT (SELECT id FROM inserted_question_2), 'Durch die Digitalisierung der Arbeitswelt, die zu zeitlicher und räumlicher Flexibilisierung führt.', true, 'Das Dokument beschreibt Arbeit 4.0 als "Digitalisierung der Arbeitswelt", die eine "zeitlich und räumlich nahezu unbegrenztes Arbeiten" schafft.

**Warum andere falsch:** B, C und D beschreiben das genaue Gegenteil der Merkmale von Arbeit 4.0.

**💡 Wichtige Erkenntnis:** Arbeit 4.0 beschreibt den Wandel der Arbeitswelt durch digitale Technologien, Vernetzung und Flexibilisierung.' UNION ALL SELECT (SELECT id FROM inserted_question_2), 'Durch die Rückkehr zu traditionellen Handwerksberufen und manueller Fertigung.', false, NULL UNION ALL SELECT (SELECT id FROM inserted_question_2), 'Durch die strikte Trennung von Arbeitszeit und Freizeit (9-to-5-Job).', false, NULL UNION ALL SELECT (SELECT id FROM inserted_question_2), 'Durch die ausschließliche Nutzung von analogen Werkzeugen und PapierdDokumenten.', false, NULL;
WITH inserted_question_3 AS (INSERT INTO questions (quiz_id, question_text, question_type, expected_answer, order_index) VALUES ('37d31e3a-0528-4801-b946-cb76d8c80a9b', '**Sicherheitskennzeichen**

Welchem Zweck dient die Sicherheitskennzeichnung nach DIN EN ISO 7010 und ASR A1.3?', 'MCQ', NULL, 4) ON CONFLICT DO NOTHING RETURNING id) INSERT INTO options (question_id, option_text, is_correct, explanation) SELECT (SELECT id FROM inserted_question_3), 'Der Dekoration von Arbeitsstätten und der Steigerung des Wohlbefindens.', false, NULL UNION ALL SELECT (SELECT id FROM inserted_question_3), 'Der Unfallverhütung und dem Gesundheitsschutz am Arbeitsplatz .', true, 'Das Dokument besagt, dass "Die Verwendung von Sicherheitskennzeichen ... der Unfallverhütung und dem Gesundheitsschutz am Arbeitsplatz" dient . Die ASR A1.3 regelt die Mindestvorschriften dafür.

**Warum andere falsch:** A, C und D sind entweder falsch oder zu stark eingeschränkt. Sicherheitszeichen umfassen mehr als nur Fluchtwege (z.B. auch Warn- und Verbotszeichen).

**💡 Wichtige Erkenntnis:** Sicherheitskennzeichen sind eine universelle, piktogrammbasierte Sprache, um schnell auf Gefahren hinzuweisen oder Gebote/Verbote zu kommunizieren.' UNION ALL SELECT (SELECT id FROM inserted_question_3), 'Der Kennzeichnung von Fluchtwegen ausschließlich im Brandfall.', false, NULL UNION ALL SELECT (SELECT id FROM inserted_question_3), 'Der Identifizierung von Mitarbeitern verschiedener Abteilungen durch Farbcodes.', false, NULL;
INSERT INTO enabler_quiz_links (enabler_id, quiz_id, difficulty) VALUES ('10d2e4f6-39d0-445e-88bf-948765e3adbd', '37d31e3a-0528-4801-b946-cb76d8c80a9b', 'LOW') ON CONFLICT DO NOTHING;